### PR TITLE
Continuing work in Display List / Graphics intitialization

### PR DESCRIPTION
**Pull request by michaelsternberg**
Hi. I think I'm getting better at keeping my fork up-to-date with the upstream master. So I have a set of commits ready.

I'll continue working in the display list / graphics setup.

### CODE REVIEW

**Comment by michaelsternberg** [comment]
Thanks

**Comment by jduerstock** [comment]
Thanks for all your work. :)

**Comment by jduerstock** [comment]
Any strong feelings about whether to break out the font bits into separate files or not?

**Comment by michaelsternberg** [comment]
I don’t have a strong opinion. 

I really like the Rstring macro. It had me thinking of other macros. Low priority, but at some point I’d like to try to create a macro that converts the easier-to-visualize bitfield representation currently in the comment section into a binary string.  

Something like:

Bitfield ..####..

Assembles to:

.byte %00111100

**Pull request merged**
